//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Java21.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int id { get; set; }
        public string title { get; set; }
        public int category { get; set; }
        public string artical { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public string cuser { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public string euser { get; set; }
        public Nullable<System.DateTime> comment { get; set; }
        public int cread { get; set; }
        public bool valid { get; set; }
    }
}
