//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Java21.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id { get; set; }
        public int aid { get; set; }
        public string uid { get; set; }
        public int star { get; set; }
        public string comment1 { get; set; }
        public System.DateTime cdate { get; set; }
        public string device { get; set; }
    }
}
