//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Java21.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keys
    {
        public int id { get; set; }
        public string keys1 { get; set; }
        public int maxc { get; set; }
        public int curr { get; set; }
        public string ver { get; set; }
        public System.DateTime cdate { get; set; }
        public string mark { get; set; }
    }
}
