//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Java21.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public string name { get; set; }
        public string psd { get; set; }
        public int roles { get; set; }
        public string nickname { get; set; }
        public bool gender { get; set; }
        public string email { get; set; }
        public bool valid { get; set; }
        public System.DateTime cdate { get; set; }
        public string mark { get; set; }
        public string head { get; set; }
    }
}
